// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wallet_guardian_backend.Data;

#nullable disable

namespace wallet_guardian_backend.Migrations
{
    [DbContext(typeof(WalletGuardianDbContext))]
    partial class WalletGuardianDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("wallet_guardian_backend.Data.Kategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("Icon")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Kategories", "WalletGuardianAPIDb");
                });

            modelBuilder.Entity("wallet_guardian_backend.Data.MonthlyBudgetStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("AdditionalIncomes")
                        .HasColumnType("double");

                    b.Property<double>("CarOdometerReadingFirstDayOfMonth")
                        .HasColumnType("double");

                    b.Property<double>("CarOdometerReadingLastDayOfMonth")
                        .HasColumnType("double");

                    b.Property<double>("Income")
                        .HasColumnType("double");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MonthlyBudgetStatistics", "WalletGuardianAPIDb");
                });

            modelBuilder.Entity("wallet_guardian_backend.Data.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("BillCost")
                        .HasColumnType("double");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("MonthlyBudgetStatisticId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MonthlyBudgetStatisticId");

                    b.HasIndex("ShopId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Purchases", "WalletGuardianAPIDb");
                });

            modelBuilder.Entity("wallet_guardian_backend.Data.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Shops", "WalletGuardianAPIDb");
                });

            modelBuilder.Entity("wallet_guardian_backend.Data.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("KategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("OnceAYear")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("KategoryId");

                    b.ToTable("Subcategories", "WalletGuardianAPIDb");
                });

            modelBuilder.Entity("wallet_guardian_backend.Data.Purchase", b =>
                {
                    b.HasOne("wallet_guardian_backend.Data.Kategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wallet_guardian_backend.Data.MonthlyBudgetStatistic", null)
                        .WithMany("Purchases")
                        .HasForeignKey("MonthlyBudgetStatisticId");

                    b.HasOne("wallet_guardian_backend.Data.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wallet_guardian_backend.Data.Subcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Shop");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("wallet_guardian_backend.Data.Subcategory", b =>
                {
                    b.HasOne("wallet_guardian_backend.Data.Kategory", null)
                        .WithMany("Subcategories")
                        .HasForeignKey("KategoryId");
                });

            modelBuilder.Entity("wallet_guardian_backend.Data.Kategory", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("wallet_guardian_backend.Data.MonthlyBudgetStatistic", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
